### ISSUE TITLE
HardNested单线程问题

### ISSUE THREAD

**Issue by Zy143L** [xcicode/MifareOneTool#12]
版本为 1.6.5 版本
未勾选单线程 HardNested
但是软件显示 只有单线程

可否通过例如GPU加速形式来加速破解？

**Comment by Zy143L** [comment]
自行解决了 作者注意libnfc_hardnested和libnfc_hardnestedlc的编译参数问题

**Comment by ltg2005** [comment]
> 自行解决了 作者注意libnfc_hardnested和libnfc_hardnestedlc的编译参数问题
求大神共享。。。。

**Comment by XAS-712** [comment]
v1.6.6已经修复。

**Comment by ltg2005** [comment]
使用1.6.6版本hardnest时，电脑正常状况下CPU及内存运行正常，待机运行后打开电脑，CPU100%,1.65没这个状况，为什么？？

**Comment by XAS-712** [comment]
正常。Hardnested需要大量计算，不开单线程计算则是全速运行。
