### ISSUE TITLE
是否可以公开hardnested计算程序

### ISSUE THREAD

**Issue by Zy143L** [xcicode/MifareOneTool#13]
云服务器那个貌似挂了
是否可以公开计算程序
让我们用自己的服务器进行计算

**Comment by Zy143L** [comment]
自己新编译解决了 打扰了

**Comment by ltg2005** [comment]
> 自己新编译解决了 打扰了

大神 能不能共享一下，谢谢 ltg2009@126.com

**Comment by XAS-712** [comment]
云计算重新上线成功。队列没连好。
另，自行移植到Windows需注意alarm信号处理。
源代码在crypto1_bs仓库。

**Comment by Holdmyhand** [comment]
> 自己新编译解决了 打扰了

可否分享下

**Comment by XAS-712** [comment]
> > 自己新编译解决了 打扰了
> 
> 可否分享下

请注意看你楼上的回复。

**Comment by eocene317** [comment]
> > > 自己新编译解决了 打扰了
> > 
> > 
> > 可否分享下
> 
> 请注意看你楼上的回复。

crypto1_bs 可以处理的是bin文件或者txt文件，请问nbf文件如何处理呢？谢谢

**Comment by denghuinow** [comment]
> > > > 自己新编译解决了打扰了
> > > 
> > > 
> > > 可否分享下
> > 
> > 
> > 请注意看你楼上的回复。
> 
> crypto1_bs可以处理的是bin文件或者txt文件，请问nbf文件如何处理呢？谢谢

同问

**Comment by rinscr3003** [comment]
> > > > > 自己新编译解决了打扰了
> > > > 
> > > > 
> > > > 可否分享下
> > > 
> > > 
> > > 请注意看你楼上的回复。
> > 
> > 
> > crypto1_bs可以处理的是bin文件或者txt文件，请问nbf文件如何处理呢？谢谢
> 
> 同问

大概是不行，似乎文件经过加密，而且说是非标算法，是一个大神提供的加密方案
