### ISSUE TITLE
关于COM查找的问题

### ISSUE THREAD

**Issue by Zy143L** [xcicode/MifareOneTool#14]
建议允许用户 自己选择COM端口 
例如我使用的是蓝牙Pn532 使用指定COM号配置文件的mfoc均可使用
您的程序似乎无法查找到蓝牙com端口
是否可以允许自定义com呢

**Comment by XAS-712** [comment]
复制一个配置文件放在软件程序同目录下并写好串口号即可。

**Comment by Zy143L** [comment]
失败QAQ...但是单独编译拿出来的就ok

**Comment by XAS-712** [comment]
还有一个方法。用有线设备连好后改配置文件。只要不再重新扫描就不会覆盖原文件。

**Comment by XAS-712** [comment]
配置文件名是libnfc.conf，与nfc-bin文件夹同级。

**Comment by XAS-712** [comment]
较长时间没有测试回复，暂时关闭issue
