### ISSUE TITLE
使用过程有点问题

### ISSUE THREAD

**Issue by heham** [xcicode/MifareOneTool#15]
非常感谢你的程序，使用上出了点问题寻求帮助。
1.买的UID卡，手机上用mct可以正常写，除了0区吧，但是这些卡有的或有时在程序里识别不出来。
2.识别出来的UID号改写不成功。
3.还有一个CUID卡，当时误操作在手机上把0扇区全部填0了，现在手机不能识别，但是用蛐蛐的那个可以读，就是不能写0区了，这个卡在你的程序上也识别不了。

**Comment by heham** [comment]
忘了说，我用的ch341a的ttl板接pn532硬件应该1.6版的

**Comment by XAS-712** [comment]
1 尝试检查卡片通信状况
2 uid号改写不成功是否提示后门指令无响应？
3 cuid的0区全部写0会导致卡类型识别无效，因此卡片无法再写入（除非使用pm3强写0块）

**Comment by heham** [comment]
> 1 尝试检查卡片通信状况
> 2 uid号改写不成功是否提示后门指令无响应？这说明不是uid卡。
> 3 cuid的0区全部写0会导致卡类型识别无效，因此卡片无法再写入（除非使用pm3强写0块）

感谢，通信正常是没问题的，卡片检测的时候提示是uid卡，有提示后门的，最后能不能支持一下0区的任意擦写？就是可以复制后0区和之前的卡一样

**Comment by XAS-712** [comment]
写卡选择UID写即可。
另，我制作了一个1k卡强写程序，可以用mff08来实现强行救卡。

解决方法：
下载mff08.exe，放置于nfc-bin文件夹内。
用内置的hex编辑器新建一个文件，另存为在nfc-bin文件夹内，文件名为empty.mfd。
找出最后一次成功写入该卡的数据文件（即导致写错0块的数据文件），复制到nfc-bin文件夹内，文件名为key.mfd。
做好以上准备工作后，转到高级操作模式，点击手动CLI进入NFC工具命令行。
输入：mff08.exe c C u empty.mfd key.mfd f
然后回车。

[mff08.zip](https://github.com/xcicode/MifareOneTool/files/3133431/mff08.zip)

**Comment by heham** [comment]
> 写卡选择UID写即可。
> 另，我制作了一个1k卡强写程序，可以用mff08来实现强行救卡。
> 解决方法：
> 下载mff08.exe，放置于nfc-bin文件夹内。
> 用内置的hex编辑器新建一个文件，另存为在nfc-bin文件夹内，文件名为empty.mfd。
> 找出最后一次成功写入该卡的数据文件（即导致写错0块的数据文件），复制到nfc-bin文件夹内，文件名为key.mfd。
> 做好以上准备工作后，转到高级操作模式，点击手动CLI进入NFC工具命令行。
> 输入：mff08.exe c C u empty.mfd key.mfd f
> 然后回车。
> mff08.zip

非常感谢，已经弄好了。另外可能是卡的原因，我手上的UID估计种类不一样，有的可以在软件里正常读写，有的直接就识别不出来，识别不出来的卡在手机上MCT除0扇区外读写正常。手机上读出来除了序列号以外其他都是一样的ISO 14443-3A的卡。这就很奇怪了，如果方便的话能不能分析下原因提高下对卡的兼容性。

**Comment by XAS-712** [comment]
控制位第四字节是用户保留，不参与控制位的解析。因此逻辑上两张卡控制位一样。

**Comment by fuuhoo** [comment]
> 写卡选择UID写即可。 另，我制作了一个1k卡强写程序，可以用mff08来实现强行救卡。
> 
> 解决方法： 下载mff08.exe，放置于nfc-bin文件夹内。 用内置的hex编辑器新建一个文件，另存为在nfc-bin文件夹内，文件名为empty.mfd。 找出最后一次成功写入该卡的数据文件（即导致写错0块的数据文件），复制到nfc-bin文件夹内，文件名为key.mfd。 做好以上准备工作后，转到高级操作模式，点击手动CLI进入NFC工具命令行。 输入：mff08.exe c C u empty.mfd key.mfd f 然后回车。
> 
> [mff08.zip](https://github.com/xcicode/MifareOneTool/files/3133431/mff08.zip)

能救其他扇区的控制位全是0的情况吗？
