### ISSUE TITLE
1.7.0.0tag以后的界面布局太过雷人

### ISSUE THREAD

**Issue by rinscr3003** [xcicode/MifareOneTool#25]
不能好好设计下嘛，最新提交的界面布局简直要跪了
还远不如v1.7.0.0的tag那一版
只会下载release不会自己编译最新提交的请不要乱操作，这里说的是最新提交不是你用的旧成品版本，喷人要有逻辑支持。

**Comment by Zrincet** [comment]
项目是开源的，你可以自己去改你喜欢的布局，而不是在这里开喷。

**Comment by rinscr3003** [comment]
，，，，。。。。
我说的是最新的master上的提交
为避免歧义已补充问题

> 项目是开源的，你可以自己去改你喜欢的布局，而不是在这里开喷。

请问你说的是最新提交还是v1.7.0.0那个tag的版本？  
v1.7.0.0的设计没有严重问题，但是最新提交你下载下来看看？强行多语言支持导致界面尺寸失调，而作者直接合并更改了？？？？  
幸好作者还把一堆无用的事件函数删了：。
![964FE0B9-0999-4944-836E-DFF7779917ED](https://user-images.githubusercontent.com/50514886/64009299-2fb63700-cb4a-11e9-9cd0-c7e6f12b077e.png) 
否则还以为这是作者干的好事，不进来翻完issue谁会知道这些鬼代码是国际化的时候合并进来的？  
另一方面这个hardnested怎么了？？？
![88530E1C-D5D4-4F90-A46F-94BE14F2AB0C](https://user-images.githubusercontent.com/50514886/64009847-3a250080-cb4b-11e9-876e-0138e522abba.png)
好好的单核心计算模式和保护代码为啥要删了？？？嗯？
单核心计算对于丢在后台跑密码的用户是刚需。
lprocess这个变量是表示是否正在运行，作者设计lprocess的目的应该就是防止误操作。
结果把防止误操作代码给删了？
作者恐怕合并代码的时候根本没有用心检查吧。
没必要洗，提交记录都摆着。

幸好作者没把最新的提交给编译了发release，否则恐怕有损形象。

我不否认v1.7.0.0及以前的版本是优秀的nfc软件，是国产nfc软件中功能最强的，但是也请用心做好v1.7.0.0以后的版本（如果还有）。开源自然是好事，接受别人的好意时也要检查一下有没有有意或无意的错误。
另外，建议以后作者合并分支到test，测试通过后再合并到master，防止惨案。

**Comment by XAS-712** [comment]
Thanks for your advice.
