### ISSUE TITLE
Mfoc2.exe

### ISSUE THREAD

**Issue by stef60** [xcicode/MifareOneTool#27]
Hello,

Well done for your work.
I would like to know which version of mfoc did you work to make the mfoc2.exe because with I manage to find the keys of new tnp3xxx.

thank you in advance

**Comment by rinscr3003** [comment]
It seems that Mfoc2.exe is never used.
It might be a development built. But it doesn’t work in some cases that Mfoc.exe can normally work.

**Comment by XAS-712** [comment]
It's a test build. Never used in releases.
