### ISSUE TITLE
报错：无法读取密钥文件: cuid_empty.kmf

### ISSUE THREAD

**Issue by Zzx-J** [xcicode/MifareOneTool#36]
**描述一下bug**
使用cuid写时出现报错
读卡器连接正常
卡片正常

**如何重现这个bug呢？**

使用cuid写功能将已破解的dump文件写入卡或手机时报错：无法读取密钥文件: cuid_empty.kmf

**截屏**

NFC设备: NFC-Device 已打开
已找到Mifare Classic卡片:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  02  
       UID (NFCID1): a9  fb  b9  34  
      SAK (SEL_RES): 08  
推测大小: 可能是 4096-byte 大小的卡片
无法读取密钥文件: cuid_empty.kmf

![image](https://user-images.githubusercontent.com/82952761/127433522-b40251ab-c5f1-4de6-b470-f5772395833e.png)

**环境 (请填表):**
 - 操作系统: win10
 - 读写器型号 PN532
 - 连接线型号 CH340G
 - 软件版本 v1.7.0.0
 - 操作的卡片 CUID 、手机

**还有什么想说的？**
无论是换卡片还是换手机，反复试了几次报错相同
卡片和手机都是能写入的

**Comment by thietdang** [comment]
Hello Zhao Zexing.
Can you give me contact information?

**Comment by thietdang** [comment]
I need support for you with MasterFOC in your github.
Thank you so much.

**Comment by thietdang** [comment]
Hello Zhao Zexing. Can you give me contact information(Email or Wechat)?
I need your support for the project MasterFOC in your github.
Thank you so much.
